### ISSUE TITLE
Is demo.csv real data or synthetic data?

### ISSUE THREAD

**Issue by mydmdm** [baichen318/boom-explorer-public#1]
The boom explorer is a great and foundational work in this area. I am investigating the feasibility of making my research based on it. 
Could you please confirm if the data listed in this file is genuine and suitable for conducting analysis and testing? And is there any way that I can access more of such data?

Thanks!

**Comment by baichen318** [comment]
Sorry for the late reply. Thank you for the comments.

I confirm the data listed in the repo (`https://github.com/baichen318/boom-explorer-public/blob/master/dataset/demo.csv`) is genuine and suitable for conducting analysis and testing. But demo.csv only lists a part rather than the entire data set.
If you need more, please get in touch with me via cbai@cse.cuhk.edu.hk.
Thank you.
